name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=sha-,enable={{is_default_branch}}
          flavor: |
            latest=false

      - name: Check if major version release
        id: check_major
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          if [[ $VERSION =~ ^[0-9]+\.0\.0$ ]]; then
            echo "is_major_release=true" >> $GITHUB_OUTPUT
            echo "This is a major version release: $VERSION"
          else
            echo "is_major_release=false" >> $GITHUB_OUTPUT
            echo "This is not a major version release: $VERSION"
          fi

      - name: Extract metadata with latest tag for major releases
        id: meta_with_latest
        if: steps.check_major.outputs.is_major_release == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest
            type=sha,prefix=sha-,enable={{is_default_branch}}
          flavor: |
            latest=false

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.check_major.outputs.is_major_release == 'true' && steps.meta_with_latest.outputs.tags || steps.meta.outputs.tags }}
          labels: ${{ steps.check_major.outputs.is_major_release == 'true' && steps.meta_with_latest.outputs.labels || steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
